---
- name: Incus - Add package repository
  hosts: all
  order: shuffle
  gather_facts: yes
  vars:
    task_release: "{{ incus_release | default('stable') }}"
    task_roles: "{{ incus_roles | default([]) }}"
  any_errors_fatal: true
  tasks:
    - name: Create apt keyring path
      file:
        path: /etc/apt/keyrings/
        mode: 0755
        state: directory
      when: 'task_roles|length > 0 and task_release != "distro"'

    - name: Add Zabbly repository key
      copy:
        src: ../files/incus/zabbly.asc
        dest: /etc/apt/keyrings/ansible-zabbly.asc
      notify: Update apt
      when: 'task_roles|length > 0 and task_release != "distro"'

    - name: Get DPKG architecture
      shell: dpkg --print-architecture
      register: dpkg_architecture
      changed_when: false
      check_mode: no
      when: 'task_roles|length > 0 and task_release != "distro"'

    - name: Add Zabbly package source
      template:
        src: ../files/incus/incus.sources.tpl
        dest: /etc/apt/sources.list.d/ansible-zabbly-incus-{{ task_release }}.sources
      notify: Update apt
      when: 'task_roles|length > 0 and task_release != "distro"'

  handlers:
    - name: Update apt
      apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 0

- name: Incus - Install packages and bootstrap
  hosts: all
  order: shuffle
  gather_facts: yes
  vars:
    task_init: "{{ incus_init | default('{}') }}"
    task_ip_address: "{{ incus_ip_address | default(ansible_default_ipv6['address'] | default(ansible_default_ipv4['address'])) }}"
    task_name: "{{ incus_name | default('') }}"
    task_roles: "{{ incus_roles | default([]) }}"

    task_ovn_northbound: "{{ lookup('template', '../files/ovn/ovn-central.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6641') | join(',') }}"
    task_servers: "{{ lookup('template', '../files/incus/incus.servers.tpl') | from_yaml | sort }}"
  any_errors_fatal: true
  tasks:
    - name: Install the Incus package
      apt:
        name:
          - incus
        install_recommends: no
        state: present
      register: install
      when: 'task_roles | length > 0'

    - name: Install the Incus UI package
      apt:
        name:
          - incus-ui-canonical
        install_recommends: no
        state: present
      when: '"ui" in task_roles'

    - name: Install btrfs tools
      apt:
        name:
          - btrfs-progs
        install_recommends: no
        state: present
      when: "task_roles | length > 0 and 'btrfs' in task_init['storage'] | dict2items | json_query('[].value.driver')"

    - name: Install ceph tools
      apt:
        name:
          - ceph-common
        install_recommends: no
        state: present
      when: "task_roles | length > 0 and 'ceph' in task_init['storage'] | dict2items | json_query('[].value.driver')"

    - name: Install LVM tools
      apt:
        name:
          - lvm2
        install_recommends: no
        state: present
      when: "task_roles | length > 0 and 'lvm' in task_init['storage'] | dict2items | json_query('[].value.driver')"

    - name: Install ZFS tools
      apt:
        name:
          - zfsutils-linux
        install_recommends: no
        state: present
      when: "task_roles | length > 0 and 'zfs' in task_init['storage'] | dict2items | json_query('[].value.driver')"

    - name: Set client listen address
      shell:
        cmd: "incus --force-local config set core.https_address {{ task_ip_address }}"
      when: 'install.changed and ("standalone" in task_roles or ("cluster" in task_roles and task_servers[0] == inventory_hostname))'

    - name: Set cluster listen address
      shell:
        cmd: "incus --force-local config set cluster.https_address {{ task_ip_address }}"
      when: 'install.changed and "cluster" in task_roles and task_servers[0] == inventory_hostname'

    - name: Set OVN NorthBound database
      shell:
        cmd: "incus --force-local config set network.ovn.northbound_connection={{ task_ovn_northbound }} network.ovn.client_cert=\"{{ lookup('file', '../data/ovn/'+ovn_name+'/'+inventory_hostname+'.crt') }}\" network.ovn.client_key=\"{{ lookup('file', '../data/ovn/'+ovn_name+'/'+inventory_hostname+'.key') }}\" network.ovn.ca_cert=\"{{ lookup('file', '../data/ovn/'+ovn_name+'/ca.crt') }}\""
      notify: Restart Incus
      when: 'install.changed and task_ovn_northbound and ("standalone" in task_roles or ("cluster" in task_roles and task_servers[0] == inventory_hostname))'

    - name: Add networks
      shell:
        cmd: "incus network create {{ item.key }} --type={{ item.value.type }}{% for k in item.value.local_config | default([]) %} {{ k }}={{ item.value.local_config[k] }}{% endfor %}{% for k in item.value.config | default([]) %} {{ k }}={{ item.value.config[k] }}{% endfor %}"
      loop: "{{ task_init['network'] | dict2items }}"
      when: 'install.changed and ("standalone" in task_roles or ("cluster" in task_roles and task_servers[0] == inventory_hostname))'

    - name: Add storage pools
      shell:
        cmd: "incus storage create {{ item.key }} {{ item.value.driver }}{% for k in item.value.local_config | default([]) %} {{ k }}={{ item.value.local_config[k] }}{% endfor %}{% for k in item.value.config | default([]) %} {{ k }}={{ item.value.config[k] }}{% endfor %}"
      loop: "{{ task_init['storage'] | dict2items }}"
      when: 'install.changed and ("standalone" in task_roles or ("cluster" in task_roles and task_servers[0] == inventory_hostname))'

    - name: Add storage pool to default profile
      shell:
        cmd: "incus profile device add default root disk path=/ pool={{ item }}"
      loop: "{{ task_init['storage'] | dict2items | json_query('[?value.default].key') }}"
      when: 'install.changed and ("standalone" in task_roles or ("cluster" in task_roles and task_servers[0] == inventory_hostname))'

    - name: Add network to default profile
      shell:
        cmd: "incus profile device add default eth0 nic network={{ item }} name=eth0"
      loop: "{{ task_init['network'] | dict2items | json_query('[?value.default].key') }}"
      when: 'install.changed and ("standalone" in task_roles or ("cluster" in task_roles and task_servers[0] == inventory_hostname))'

    - name: Bootstrap the cluster
      shell:
        cmd: "incus --force-local cluster enable {{ inventory_hostname }}"
      when: 'install.changed and "cluster" in task_roles and task_servers[0] == inventory_hostname'

    - name: Create join tokens
      delegate_to: "{{ task_servers[0] }}"
      shell:
        cmd: "incus --force-local --quiet cluster add {{ inventory_hostname }}"
      register: cluster_add
      when: 'install.changed and "cluster" in task_roles and task_servers[0] != inventory_hostname'

    - name: Join the cluster
      throttle: 1
      shell:
        cmd: "incus --force-local admin init --preseed"
        stdin: |-
          cluster:
            enabled: true
            cluster_address: "{{ task_ip_address }}"
            cluster_token: "{{ cluster_add.stdout }}"
            server_address: "{{ task_ip_address }}"
            member_config:{% for pool in task_init.storage %}{% for key in task_init.storage[pool].local_config | default([]) %}

              - entity: storage-pool
                name: {{ pool }}
                key: {{ key }}
                value: {{ task_init.storage[pool].local_config[key] }}{% endfor %}{% endfor %}{% for network in task_init.network %}{% for key in task_init.network[network].local_config | default([]) %}

              - entity: network
                name: {{ network }}
                key: {{ key }}
                value: {{ task_init.network[network].local_config[key] }}{% endfor %}{% endfor %}
      when: 'cluster_add.changed'
  handlers:
    - name: Restart Incus
      systemd:
        name: incus.service
        state: restarted
